default:
  http_metas:
    content-type: text/html

  metas:
    title:        BlueSquare project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [main.css, bootstrap.min.css]

  javascripts:    []

  has_layout:     on
  layout:         layout
