<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/07/07 16:37:01

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'host' => 'localhost',
  'database' => 'bluesquare',
  'username' => 'root',
  'password' => 'root',
  'protocol' => 'unix',
  'encoding' => 'utf8',
), 'propel');
$this->databases['propel'] = $database;
